spring:
  profiles:
    active: development
  server:
    port: 8761
---
spring:
  profiles: cloud
  neo4j:
    host: ${SPRING_NEO4J_HOST:localhost}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: Veer@123
---
spring:
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:localhost}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: Veer@123

---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:localhost}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: Veer@123
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:localhost}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: Veer@123
eureka:
  client:
    enabled: false
